apiVersion: apps/v1
kind: Deployment
metadata:
  name: budgetappapi-deployment
  labels:
    app: budgetapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: budgetapp
  template:
    metadata:
      labels:
        app: budgetapp
    spec:
      containers:
        - name: budgetapp
          image: 807602152072.dkr.ecr.us-east-1.amazonaws.com/budgetappapi:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
