apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: nginx
spec:
  controller: k8s.io/ingress-nginx
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: budgetapp-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: nginx
  rules:
    - host: "yourbudgetapp.com"
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: budgetapp-service
                port:
                  number: 80
  tls:
    - hosts:
      - yourbudgetapp.com
      secretName: budgetapp-cert

